### ISSUE TITLE
Suggestion: Add Toggle for Cardinal Directions to Cycle

### ISSUE THREAD

**Issue by Davidc145** [RaazKH/CompassCameraControl#11]
Would it be possible to add a toggle in the settings for each of the cardinal directions so that cycling can be customized? For example, if I want to only snap north and south then I could unselect east and west. Currently it's one click to look south then 3 clicks to return north.

**Comment by RaazKH** [comment]
Yeah that's possible

I'll add a text box or something which allows users to configure the cycle order and remove directions they don't want
